### ISSUE TITLE
Unable to query from Br0 and Eth0 interfaces

### ISSUE THREAD

**Issue by BugZappa** [jacklul/entware-pi-hole#3]
Edit; Using Asus WRT Merlin firmware on an Asus RT-AX86U Pro

I tried to follow this guide as closely as possible however have been having issues getting query request to pass through PiHole;

(Removed LAN IP's & Mac address information)
![image](https://github.com/user-attachments/assets/3c9699dc-33d9-4318-9205-6c00664c7e03)

My PiHole diagnostics tab is spitting two errors that i can't seem to resolve:
![image](https://github.com/user-attachments/assets/87d7b6c5-3782-4303-a64d-86caaacae3b2)

My pihole debug log (removed as much personal information as i can see)

_Removed_

**Comment by jacklul** [comment]
For the first error try setting in `/opt/etc/pihole/pihole.toml`:

```toml
[dns]
  interface = "br0"
  listeningMode = "BIND"
```

`listeningMode = "ALL"` might expose your Pi-hole to the internet if not properly firewalled.

For the second error:

```toml
[ntp.ipv4]
  active = false
  listeningMode = "BIND"
```

I'm guessing you're already running NTP server and the port is taken so that's what the error message is about.

_I've edited your message to wrap the log into expandable section to not take so much space._
